### ISSUE TITLE
A few questions on Rethinking_Soss

### ISSUE THREAD

**Issue by goedman** [kw-fn/Rethinking_Soss#1]
Hi Oliver,

Chad pointed me to your work from about 4 months ago as I am interested in trying to explore Soss versions of the rethinking models to the StatisticalRethinkingJulia Github organization. 

So I was wondering if you are planning to do further work on this? What was your experience doing these models in Soss? Do the Soss formulations help in understanding the models?

Most of this work is still in the early planning stages and is intended to ultimately result in a pure Julia version of StatisticalRethinking, maybe v2 of that package if indeed that adds value? Hence my questions.

Best,
Rob

**Comment by kw-fn** [comment]
Hi Rob,

Sorry, I totally missed your post! 

Hope all is well.
Best, Oliver

**Comment by goedman** [comment]
No problem. In 2020 I stepped a bit away from Soss because of the heavy dependency on Python. Now Symbolics.jl is becoming available maybe that could replace SymPy. Anyway, for 2021 my plate is pretty full, so RethinkingSoss is a long term idea. Thanks for getting back.

Best, Rob

**Comment by kw-fn** [comment]
I basically ran the repo locally until it breaks then made the most I could work, Re-RethinkingSoss [at this point] is an interesting idea :)

**Comment by cscherrer** [comment]
FWIW we've dropped the Python dependency. Symbolic analysis now uses SymbolicUtils. The ecosystem had also grown a lot. Check out MeasureTheory, NestedTuples, TupleVectors, SampleChainsDynamicHMC...

**Comment by goedman** [comment]
Yes, absolutely, what I see in Oliver's repo is very clean and appealing!
